/**
 * Room identity: how pi-courier names and brands the rooms it manages.
 *
 * The space is named `π <instanceName>` (short; the old `pi-courier · <name>`
 * template is migrated on startup — see isLegacySpaceName). Every managed room
 * also gets a bundled pixel avatar (assets/avatars/, generated by
 * scripts/generate-avatars.mjs — original artwork, blocky-pixel style): the
 * space picks by instanceName hash and project rooms by project name hash, so
 * each deployment lands on a stable image (recreates and restarts keep it)
 * while different instances/projects usually differ. The management room uses
 * the dedicated management.png. All artwork is original — generic blocky
 * pixel style only, no third-party assets; users can swap any PNG for their
 * own (same filename) without touching code.
 */

import { readFileSync } from "node:fs";

/** Number of images in the shared pool (instance-01 … instance-12). */
export const AVATAR_POOL_SIZE = 12;

/** Display name for the space: short instance label with a π brand prefix. */
export function spaceDisplayName(instanceName: string): string {
  return `π ${instanceName}`;
}

/** The pre-rename template. Only an EXACT match is ever renamed, so a name a
 *  user typed themselves is never clobbered by the startup self-heal. */
export function isLegacySpaceName(name: string, instanceName: string): boolean {
  return name === `pi-courier · ${instanceName}`;
}

/** djb2 over the UTF-8 bytes — tiny, stable across processes and runtimes
 *  (plain u32 arithmetic, no locale/crypto dependence). */
export function nameHash(name: string): number {
  let hash = 5381;
  for (const byte of Buffer.from(name, "utf8")) hash = (hash * 33 + byte) >>> 0;
  return hash;
}

/** Pick a pool filename for a name: same name → same image, forever. */
export function pickPoolAvatarFile(name: string): string {
  const index = (nameHash(name) % AVATAR_POOL_SIZE) + 1;
  return `instance-${String(index).padStart(2, "0")}.png`;
}

/** The management room's dedicated image (always the same, always one of a kind). */
export function managementAvatarFile(): string {
  return "management.png";
}

/** Read a bundled avatar PNG. Throws if the asset is missing — callers treat
 *  that like any other identity-heal failure (warn + retry next start). */
export function readAvatarBundled(file: string): Buffer {
  return readFileSync(avatarAssetUrl(file));
}

function avatarAssetUrl(file: string): URL {
  // src/space-identity.ts and dist/space-identity.js both sit one level below
  // the package root, so ../assets resolves in the repo and in the npm tarball.
  if (!/^[\w.-]+\.png$/.test(file)) throw new Error(`非法的头像文件名: ${file}`);
  return new URL(`../assets/avatars/${file}`, import.meta.url);
}

/** m.room.avatar `info` sub-block describing the bundled 128×128 PNGs. */
export function avatarInfo(data: Buffer): Record<string, unknown> {
  return { mimetype: "image/png", width: 128, height: 128, size: data.length };
}
